language: cpp
compiler:
  - gcc
addons:
  apt:
    packages:
      - libncursesw5-dev
      - liblua5.1-0-dev
      - pkg-config
      - libpcre3-dev
      - libgmime-2.6-dev
      - libglibmm-2.4-dev
script: make
